baseurl = ""
languageCode = "en-us"
title = "Liechi's research work"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[outputs]
    home = [ "HTML", "CSS", "RSS" ]
    section = [ "HTML", "RSS" ]

[permalinks]
    post = "/:year/:month/:day/:slug/"


[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 4
#[[menu.main]]
#    name = "Liechi's personal website"
#    url = "https://liechi.org"
#    weight = 5

[params]
    description = "A website built through Hugo and blogdown."
    customCSS = ["css/custom.css"]

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

